import 'ingredients.dart';
import 'instruction.dart';

class Autogenerated {
  List<Recipes>? recipes;

  Autogenerated({this.recipes});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['recipes'] != null) {
      recipes = <Recipes>[];
      json['recipes'].forEach((v) {
        recipes!.add(new Recipes.fromJson(v));
      });
    }
  }

  
}

class Recipes {
  String? id;
  String? cardType;
  String? title;
  String? subtitle;
  String? backgroundImage;
  String? backgroundImageSource;
  String? message;
  String? authorName;
  String? role;
  String? authorImage;
  int? durationInMinutes;
  String? dietType;
  int? calories;
  List<String>? tags;
  String? description;
  String? source;
  List<Ingredients>? ingredients;
  List<Instructions>? instructions;
  String? profileImage;
  String? chef;

  Recipes(
      {required this.id,
      required this.cardType,
      required this.title,
      required this.subtitle,
      required this.backgroundImage,
      required this.backgroundImageSource,
      required this.message,
      required this.authorName,
      required this.role,
      required this.authorImage,
      required this.durationInMinutes,
      required this.dietType,
      required this.calories,
      required this.tags,
      required this.description,
      required this.source,
      required this.ingredients,
      required this.instructions,
      required this.profileImage,
      required this.chef});

  factory Recipes.fromJson(Map<String, dynamic> json) {
    final instructions = <Instructions>[];
    final ingredients = <Ingredients>[];
    if (json['ingredients'] != null) {
      json['ingredients'].forEach((v) {
        ingredients.add(new Ingredients.fromJson(v));
      });
    }
    if (json['instructions'] != null) {
      json['instructions'].forEach((v) {
        instructions.add(new Instructions.fromJson(v));
      });
    }
    return Recipes(
      id: json['id'],
      cardType: json['cardType'],
      title: json['title'],
      subtitle: json['subtitle'],
      backgroundImage: json['backgroundImage'],
      backgroundImageSource: json['backgroundImageSource'],
      message: json['message'],
      authorName: json['authorName'],
      role: json['role'],
      authorImage: json['authorImage'],
      durationInMinutes: json['durationInMinutes'],
      dietType: json['dietType'],
      calories: json['calories'],
      tags: json['tags'].cast<String>(),
      description: json['description'],
      source: json['source'],
      profileImage: json['profileImage'],
      chef: json['chef'],
      ingredients: ingredients,
      instructions: instructions,
    );
  }

  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['id'] = this.id;
  //   data['cardType'] = this.cardType;
  //   data['title'] = this.title;
  //   data['subtitle'] = this.subtitle;
  //   data['backgroundImage'] = this.backgroundImage;
  //   data['backgroundImageSource'] = this.backgroundImageSource;
  //   data['message'] = this.message;
  //   data['authorName'] = this.authorName;
  //   data['role'] = this.role;
  //   data['authorImage'] = this.authorImage;
  //   data['durationInMinutes'] = this.durationInMinutes;
  //   data['dietType'] = this.dietType;
  //   data['calories'] = this.calories;
  //   data['tags'] = this.tags;
  //   data['description'] = this.description;
  //   data['source'] = this.source;
  //   if (this.ingredients != null) {
  //     data['ingredients'] = this.ingredients!.map((v) => v.toJson()).toList();
  //   }
  //   if (this.instructions != null) {
  //     data['instructions'] = this.instructions!.map((v) => v.toJson()).toList();
  //   }
  //   data['profileImage'] = this.profileImage;
  //   data['chef'] = this.chef;
  //   return data;
  // }
}




